# Generated by Django 5.0.6 on 2024-05-30 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chercheur',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='commentaire',
            name='date_comment',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='contenu',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='date_pub',
        ),
        migrations.AddField(
            model_name='chercheur',
            name='nom',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='chercheur',
            name='prenom',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='publication',
            name='contenu_pdf',
            field=models.FileField(default='default.pdf', upload_to='publications/'),
        ),
        migrations.AddField(
            model_name='publication',
            name='description',
            field=models.TextField(default='Unknown'),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='publications.publication'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='thematique',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='publications.thematique'),
        ),
    ]
