# Generated by Django 5.0.6 on 2024-05-30 17:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_remove_chercheur_bio_remove_commentaire_date_comment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chercheur',
            options={'ordering': ['nom', 'prenom'], 'verbose_name': 'Chercheur', 'verbose_name_plural': 'Chercheurs'},
        ),
        migrations.AlterModelOptions(
            name='commentaire',
            options={'ordering': ['-date_comment'], 'verbose_name': 'Commentaire', 'verbose_name_plural': 'Commentaires'},
        ),
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['-date_pub'], 'verbose_name': 'Publication', 'verbose_name_plural': 'Publications'},
        ),
        migrations.AlterModelOptions(
            name='thematique',
            options={'ordering': ['nom'], 'verbose_name': 'Thématique', 'verbose_name_plural': 'Thématiques'},
        ),
        migrations.AddField(
            model_name='commentaire',
            name='date_comment',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de commentaire'),
        ),
        migrations.AddField(
            model_name='publication',
            name='date_pub',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de publication'),
        ),
        migrations.AlterField(
            model_name='chercheur',
            name='nom',
            field=models.CharField(default='Unknown', max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='chercheur',
            name='prenom',
            field=models.CharField(default='Unknown', max_length=100, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='chercheur',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.chercheur', verbose_name='Auteur'),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='contenu',
            field=models.TextField(verbose_name='Contenu'),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='publications.publication', verbose_name='Publication'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.chercheur', verbose_name='Auteur'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='contenu_pdf',
            field=models.FileField(default='default.pdf', upload_to='publications/', verbose_name='Contenu PDF'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='description',
            field=models.TextField(default='Unknown', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='thematique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.thematique', verbose_name='Thématique'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='titre',
            field=models.CharField(max_length=200, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='thematique',
            name='nom',
            field=models.CharField(max_length=100, verbose_name='Nom de la Thématique'),
        ),
    ]
