# Generated by Django 5.0.6 on 2024-05-30 17:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_alter_chercheur_options_alter_commentaire_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chercheur',
            options={},
        ),
        migrations.AlterModelOptions(
            name='commentaire',
            options={},
        ),
        migrations.AlterModelOptions(
            name='publication',
            options={},
        ),
        migrations.AlterModelOptions(
            name='thematique',
            options={},
        ),
        migrations.RemoveField(
            model_name='publication',
            name='date_pub',
        ),
        migrations.AlterField(
            model_name='chercheur',
            name='nom',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='chercheur',
            name='prenom',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='chercheur',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.chercheur'),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='contenu',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='date_comment',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='publications.publication'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.chercheur'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='contenu_pdf',
            field=models.FileField(default='default.pdf', upload_to='publications/'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='description',
            field=models.TextField(default='Unknown'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='thematique',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='publications.thematique'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='titre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='thematique',
            name='nom',
            field=models.CharField(max_length=100),
        ),
    ]
