# Generated by Django 5.0.6 on 2024-06-01 15:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0005_alter_chercheur_options_alter_commentaire_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='date_publication',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de publication'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='contenu_pdf',
            field=models.FileField(blank=True, null=True, upload_to='publications/', verbose_name='Contenu PDF'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='thematique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='publications.thematique', verbose_name='Thématique'),
        ),
    ]
