# Generated by Django 5.0.6 on 2024-06-02 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0006_publication_date_publication_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Nombre de vues'),
        ),
    ]
