# Generated by Django 5.0.6 on 2024-06-02 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0008_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='favorite_publications',
            field=models.ManyToManyField(related_name='favorited_by', to='publications.publication'),
        ),
    ]
